export const ACTIONS_TYPES = {
    INPUT_HANDLE_CHANGE: "INPUT_HANDLE_CHANGE",
    DELETE_FILE_LINK: "DELETE_FILE_LINK",
    INPUT_DESCRIPTION_CHANGE: "INPUT_DESCRIPTION_CHANGE",
    EDITITING_TODO_ID: "EDITITING_TODO_ID",
    SET_EDIT_MODE: "SET_EDIT_MODE",
    ADD_TODO: "ADD_TODO",
    DELETE_TODO: "DELETE_TODO",
    SET_COMPLETE_TODO: "SET_COMPLETE_TODO",
    CLEAR_COMPLETED: "CLEAR_COMPLETED",
    UPDATE_TODO: "UPDATE_TODO"
}